

services:
  api:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./token.json:/app/token.json

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
